// <auto-generated />
using System;
using BlazorCRUDSSR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUDSSR.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240302204527_twotime")]
    partial class twotime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCRUDSSR.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FavoriteGameId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteGameId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1974,
                            City = "Ljusne",
                            FirstName = "Lars",
                            LastName = "Asplund"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1964,
                            City = "Sandarne",
                            FirstName = "Nisse",
                            LastName = "Manpower"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1988,
                            City = "Vallvik",
                            FirstName = "Frida",
                            LastName = "Edvinsson"
                        });
                });

            modelBuilder.Entity("BlazorCRUDSSR.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publisher = "CD Project",
                            ReleaseYear = 1998,
                            Title = "CyberPunk"
                        },
                        new
                        {
                            Id = 2,
                            Publisher = "X-Corp",
                            ReleaseYear = 1999,
                            Title = "ElderRing"
                        },
                        new
                        {
                            Id = 3,
                            Publisher = "Nintendo",
                            ReleaseYear = 1988,
                            Title = "Zelda"
                        });
                });

            modelBuilder.Entity("BlazorCRUDSSR.Models.Person", b =>
                {
                    b.HasOne("BlazorCRUDSSR.Models.VideoGame", "FavoriteGame")
                        .WithMany()
                        .HasForeignKey("FavoriteGameId");

                    b.Navigation("FavoriteGame");
                });
#pragma warning restore 612, 618
        }
    }
}
